name: Build & Tests

on:
  push:
    branches:  '**'
  pull_request:
    branches:  '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
    - name: Test with unittest and coverage-report
      run: |
        coverage run --branch --include 'app/*' -m unittest discover
        coverage report
        coverage xml
    - name: Upload Coverage to Codecov
      timeout-minutes: 1
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
        verbose: true
        files: ./coverage.xml
        flags: unittests
    - name: Check code style
      run: black --check .